language: c
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.10
os:
  - linux
dist: xenial
cache:
  directories:
    - $HOME/ocaml
    - $HOME/.opam
